name: Deploy

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install -r requirements-test.txt
        pytest -s
    - name: Deploy
      run: |
        pip install twine
        python setup.py sdist
        twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u ${{secrets.pypi_username}} -p ${{secrets.pypi_password}}
